# Generated by Django 3.2.3 on 2021-07-15 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direct_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person1', to=settings.AUTH_USER_MODEL)),
                ('person_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
