# Generated by Django 3.2.3 on 2021-07-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_direct_message_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct_message',
            name='seen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat_room.direct_message')),
            ],
        ),
    ]
