# Generated by Django 3.2.3 on 2021-07-17 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_room', '0003_auto_20210717_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='direct_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat_room.direct_message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
    ]
