# Generated by Django 3.2.3 on 2021-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0004_auto_20210717_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='direct_message',
        ),
        migrations.AddField(
            model_name='message',
            name='direct_message',
            field=models.ManyToManyField(blank=True, null=True, related_name='message', to='chat_room.Direct_message'),
        ),
    ]
