# Generated by Django 3.2.3 on 2021-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='post_file',
            field=models.TextField(blank=True),
        ),
    ]
