# Generated by Django 3.2.3 on 2021-07-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_saved_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='post_file',
        ),
    ]
