# Generated by Django 3.2.3 on 2021-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='following',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='following',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
