# Generated by Django 3.2.3 on 2021-07-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210703_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='born_in',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='lives_in',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
