# Generated by Django 3.2.3 on 2021-07-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210704_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profilePic',
            field=models.TextField(blank=True),
        ),
    ]
