# Generated by Django 3.2.3 on 2021-07-07 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='followers',
            new_name='follower_count',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='following',
            new_name='following_count',
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('profilePic', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
