# Generated by Django 3.2.3 on 2021-07-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210708_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilePic',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
